blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/stvhay/glinet-comet-reverse-gpl/discussions
    about: For questions, ideas, or general discussion about the project
